/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Comment: typeof import('./components/Comment.vue')['default']
    CommentInput: typeof import('./components/CommentInput.vue')['default']
    DevConfig: typeof import('./components/settings/DevConfig.vue')['default']
    Drauu: typeof import('./components/Drauu.vue')['default']
    Friends_index: typeof import('./components/FriendsMemo.vue')['default']
    FriendsCommentInput: typeof import('./components/themes/FriendsCommentInput.vue')['default']
    FriendsMemo: typeof import('./components/themes/FriendsMemo.vue')['default']
    FriendsMemoInput: typeof import('./components/themes/FriendsMemoInput.vue')['default']
    Import: typeof import('./components/settings/Import.vue')['default']
    LeftNav: typeof import('./components/LeftNav.vue')['default']
    MarkdownInput: typeof import('./components/Markdown-input.vue')['default']
    MeAll: typeof import('./components/MeAll.vue')['default']
    Memo: typeof import('./components/Memo.vue')['default']
    MemoInput: typeof import('./components/MemoInput.vue')['default']
    Mine: typeof import('./components/Mine.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NImage: typeof import('naive-ui')['NImage']
    NImageGroup: typeof import('naive-ui')['NImageGroup']
    NInput: typeof import('naive-ui')['NInput']
    NMention: typeof import('naive-ui')['NMention']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NUpload: typeof import('naive-ui')['NUpload']
    RightNav: typeof import('./components/RightNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Statistics: typeof import('./components/Statistics.vue')['default']
    SysConfig: typeof import('./components/settings/SysConfig.vue')['default']
    TagManage: typeof import('./components/settings/TagManage.vue')['default']
    Top10Tag: typeof import('./components/Top10Tag.vue')['default']
    UserConfig: typeof import('./components/settings/UserConfig.vue')['default']
  }
}
